/**
 * leopard-api-client
 * 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 493788939lizhaogai@163.com
 *
 * NOTE: This library is auto generated by the Open API Codegen program.
 * https://github.com/taoyuan/generator-oac.git
 * Do not edit the class manually.
 *
 */

const Requestor = require('./lib/_requestor');
const Account = require('./lib/Account');
const Verification = require('./lib/Verification');
const Customer = require('./lib/Customer');
const Contact = require('./lib/Contact');
const Weibo = require('./lib/Weibo');
const BankAccount = require('./lib/BankAccount');
const SalesPlan = require('./lib/SalesPlan');
const Department = require('./lib/Department');
const CustomerIncomeExpenditure = require('./lib/CustomerIncomeExpenditure');
const WeiboRecharge = require('./lib/WeiboRecharge');
const CustomerRecharge = require('./lib/CustomerRecharge');
const CustomerBalance = require('./lib/CustomerBalance');
const WeiboIncomeExpenditure = require('./lib/WeiboIncomeExpenditure');
const WeiboBalance = require('./lib/WeiboBalance');
const Group = require('./lib/Group');
const OperationDaily = require('./lib/OperationDaily');
const Common = require('./lib/Common');
/**
 * 
 *
 * @param {String|Object} [baseUrl]
 * @param {Object} [opts]
 */
module.exports = function(baseUrl, opts) {
  if (typeof baseUrl === 'object') {
    opts = baseUrl;
    baseUrl = undefined;
  }
  opts = opts || {};
  opts.baseUrl = opts.baseUrl || baseUrl;

  const client = {};
  const requestor = client.requestor = new Requestor(opts);

  client.authenticate = function(options) {
    requestor.auth(options);
  };

  client.configure = function(options) {
    requestor.configure(options);
  };

  client.account = new Account(requestor);
  client.verification = new Verification(requestor);
  client.customer = new Customer(requestor);
  client.contact = new Contact(requestor);
  client.weibo = new Weibo(requestor);
  client.bankAccount = new BankAccount(requestor);
  client.salesPlan = new SalesPlan(requestor);
  client.department = new Department(requestor);
  client.customerIncomeExpenditure = new CustomerIncomeExpenditure(requestor);
  client.weiboRecharge = new WeiboRecharge(requestor);
  client.customerRecharge = new CustomerRecharge(requestor);
  client.customerBalance = new CustomerBalance(requestor);
  client.weiboIncomeExpenditure = new WeiboIncomeExpenditure(requestor);
  client.weiboBalance = new WeiboBalance(requestor);
  client.group = new Group(requestor);
  client.operationDaily = new OperationDaily(requestor);
  client.common = new Common(requestor);

  return client;
};